version: '3.8'
services:
  instagram2discord:
    image: iamtakagi/instagram2discord
    environment:
      TZ: Asia/Tokyo
      USERNAME: xxx
      WEBHOOK_URL: https://discord.com/api/webhooks/xxx/xxx
      TIME_INTERVAL: 600
    volumes:
      - ./data:/app/data
    restart: unless-stopped